#include "Rules.h"

Rules::Rules()
{
    datas = {
        Item(0,  "Sword's az",     ItemType::Weapon,         ItemRarity::Common),
        Item(1,  "Sword's az",     ItemType::Weapon,         ItemRarity::Common),
        Item(2,  "Gun",            ItemType::Weapon,         ItemRarity::Rare),
        Item(3,  "Machine Gun",    ItemType::Weapon,         ItemRarity::Epic),
        Item(5,  "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(6,  "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(7,  "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(8,  "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(9,  "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(10, "Gatg0 aid",      ItemType::Weapon,         ItemRarity::Legendary),
        Item(11, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(12, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(13, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(14, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(15, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(16, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(17, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(18, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(19, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(20, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(21, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(22, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(23, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(24, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(25, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(26, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(27, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(28, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(29, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(30, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(31, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(32, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(33, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(34, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(35, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(36, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(37, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(38, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(39, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(40, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(41, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(42, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(43, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(44, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(45, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(46, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(47, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(48, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(49, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(50, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(51, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(52, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(53, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(54, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(55, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(56, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(57, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(58, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(59, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(60, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(61, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(62, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(63, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(64, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(65, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(66, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(67, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(68, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(69, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(70, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(71, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(72, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(73, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(74, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(75, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(76, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(77, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(78, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(79, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(80, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(81, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(82, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(83, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(84, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(85, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(86, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(87, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(88, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(89, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(90, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(91, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(92, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(93, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(94, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(95, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(96, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(97, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(98, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(99, "Gatgaid",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(200,"Shielder",        ItemType::Weapon,         ItemRarity::Legendary),
        Item(201,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(202,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(203,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(204,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(205,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(206,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(207,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(208,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(209,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(210,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(211,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(212,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(213,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(214,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(215,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(216,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(217,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(218,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(219,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(220,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(221,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(222,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(223,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(224,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(225,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(226,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(227,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(228,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(229,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(230,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(231,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(232,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(233,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(234,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(235,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(236,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(237,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(238,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(239,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(240,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(241,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(242,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(243,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(244,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(245,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(246,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(247,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(248,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(249,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(250,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(251,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(252,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(253,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(254,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(255,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(256,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(257,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(258,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(259,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(260,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(261,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(262,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(263,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(264,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(265,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(266,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(267,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(268,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(269,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(270,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(271,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(272,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(273,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(274,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(275,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(276,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(277,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(278,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(279,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(289,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(280,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(281,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(282,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(283,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(284,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(285,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(286,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(287,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(288,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(289,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(290,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(291,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(292,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(293,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(294,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(295,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(296,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(297,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(298,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(299,"Shielder",       ItemType::Module,         ItemRarity::Common),
        Item(300,"Common Chest",   ItemType::Chest,          ItemRarity::Common),
        Item(301,"Common Chest",   ItemType::Chest,          ItemRarity::Common),
        Item(302,"RareChest",      ItemType::Chest,          ItemRarity::Rare),
        Item(303,"Epic Chest",     ItemType::Chest,          ItemRarity::Epic),
        Item(304,"Legendary Chest",ItemType::Chest,          ItemRarity::Legendary),
        Item(401,"Money",          ItemType::Money,          ItemRarity::Common),
        Item(402,"Money",          ItemType::Money,          ItemRarity::Rare),
        Item(403,"Money",          ItemType::Money,          ItemRarity::Epic),
        Item(404,"Money",          ItemType::Money,          ItemRarity::Legendary),

    };
}

void Rules::printItems() const
{
    for (const auto& item : datas)
    {
        std::cout << "ID: " << item.id << ", Name: " << item.name << ", Type: " << item.type << ", Rarity: " << item.rarity << std::endl;
    }
}

Item Rules::getItemByInfoDropRules(ItemType type, ItemRarity rarity) const
{
    vector<Item> filteritems = {};

    for (const auto& item : datas)
    {
        if (item.type == type && item.rarity == rarity)
        {
            filteritems.push_back(item);
        }
    }

    if (!filteritems.empty())
    {
        return filteritems.front();
    }
    else{
        return filteritems.at(Random::getInt(0, (filteritems.size() - 1)));
    }

    return Item();
}

Rules::~Rules()
{

}